-- Generated by scripts/moonlit-theme.py; edit palette.json.
-- Run after the existing init.lua. No mappings, plugin, font, or workflow changes.
local c = {
  background = "#18131f",
  surface = "#251d30",
  foreground = "#f1e8f1",
  muted = "#c3b3c8",
  primary = "#e6abc8",
  secondary = "#bdaee5",
  outline = "#59465f",
  selected = "#433047",
  success = "#a6c7ae",
  error = "#ed91a7",
  warning = "#e7c08f",
  blue = "#aebfec",
  cyan = "#9fcbd1",
}
local hi = function(group, value) vim.api.nvim_set_hl(0, group, value) end
hi("Normal", { fg = c.foreground, bg = "NONE" })
hi("NormalNC", { fg = c.foreground, bg = "NONE" })
hi("NormalFloat", { fg = c.foreground, bg = c.surface })
hi("FloatBorder", { fg = c.outline, bg = c.surface })
hi("FloatTitle", { fg = c.primary, bg = c.surface, bold = true })
hi("SignColumn", { fg = c.muted, bg = "NONE" })
hi("LineNr", { fg = c.muted, bg = "NONE" })
hi("CursorLineNr", { fg = c.primary, bg = "NONE", bold = true })
hi("CursorLine", { bg = c.surface })
hi("Visual", { bg = c.selected })
hi("Search", { fg = c.background, bg = c.warning })
hi("IncSearch", { fg = c.background, bg = c.primary })
hi("StatusLine", { fg = c.foreground, bg = c.surface })
hi("StatusLineNC", { fg = c.muted, bg = c.surface })
hi("WinSeparator", { fg = c.outline })
hi("Pmenu", { fg = c.foreground, bg = c.surface })
hi("PmenuSel", { fg = c.foreground, bg = c.selected })
hi("TabLine", { fg = c.muted, bg = c.surface })
hi("TabLineSel", { fg = c.background, bg = c.primary, bold = true })
hi("TabLineFill", { bg = c.background })
hi("Comment", { fg = c.muted, italic = true })
hi("String", { fg = c.success })
hi("Character", { fg = c.success })
hi("Number", { fg = c.warning })
hi("Boolean", { fg = c.warning })
hi("Constant", { fg = c.warning })
hi("Identifier", { fg = c.foreground })
hi("Function", { fg = c.blue })
hi("Statement", { fg = c.secondary })
hi("Keyword", { fg = c.secondary })
hi("Type", { fg = c.cyan })
hi("Special", { fg = c.primary })
hi("PreProc", { fg = c.primary })
hi("Title", { fg = c.primary, bold = true })
hi("Directory", { fg = c.blue })
hi("ErrorMsg", { fg = c.error })
hi("WarningMsg", { fg = c.warning })
hi("MoreMsg", { fg = c.success })
hi("DiffAdd", { fg = c.success, bg = c.surface })
hi("DiffDelete", { fg = c.error, bg = c.surface })
hi("DiffChange", { fg = c.blue, bg = c.surface })
hi("DiffText", { fg = c.foreground, bg = c.selected })
for suffix, color in pairs({ Error = c.error, Warn = c.warning, Info = c.blue, Hint = c.cyan, Ok = c.success }) do
  hi("Diagnostic" .. suffix, { fg = color })
  hi("DiagnosticSign" .. suffix, { fg = color, bg = "NONE" })
  hi("DiagnosticVirtualText" .. suffix, { fg = color, bg = c.surface })
  hi("DiagnosticUnderline" .. suffix, { sp = color, undercurl = true })
end
for group, target in pairs({ ["@keyword"] = "Keyword", ["@function"] = "Function", ["@type"] = "Type", ["@string"] = "String", ["@comment"] = "Comment", ["@number"] = "Number" }) do
  hi(group, { link = target })
end
vim.g.terminal_color_0 = "#18131f"
vim.g.terminal_color_1 = "#ed91a7"
vim.g.terminal_color_2 = "#a6c7ae"
vim.g.terminal_color_3 = "#e7c08f"
vim.g.terminal_color_4 = "#aebfec"
vim.g.terminal_color_5 = "#bdaee5"
vim.g.terminal_color_6 = "#9fcbd1"
vim.g.terminal_color_7 = "#f1e8f1"
vim.g.terminal_color_8 = "#c3b3c8"
vim.g.terminal_color_9 = "#ed91a7"
vim.g.terminal_color_10 = "#a6c7ae"
vim.g.terminal_color_11 = "#e7c08f"
vim.g.terminal_color_12 = "#aebfec"
vim.g.terminal_color_13 = "#bdaee5"
vim.g.terminal_color_14 = "#9fcbd1"
vim.g.terminal_color_15 = "#f1e8f1"
