#!/usr/bin/env python3
"""Generate opt-in desktop preview themes from config/moonlit/palette.json.

Only the four declared files under config/moonlit are written. --check validates
readability and reports generated-file drift without changing any file. Contrast
ratios describe solid swatches, not text composited over a live wallpaper.
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROLES = (
    "background", "surface", "foreground", "muted", "primary", "secondary",
    "outline", "selected", "success", "error", "warning", "blue", "cyan",
)
OUTPUTS = ("palettes/MoonlitBloom.json", "kitty-theme.conf", "nvim-theme.lua", "niri-theme.kdl")


def luminance(color: str) -> float:
    channels = [int(color[i:i + 2], 16) / 255 for i in (1, 3, 5)]
    linear = [x / 12.92 if x <= 0.04045 else ((x + 0.055) / 1.055) ** 2.4 for x in channels]
    return sum(x * weight for x, weight in zip(linear, (0.2126, 0.7152, 0.0722)))


def contrast(foreground: str, background: str) -> float:
    light, dark = sorted((luminance(foreground), luminance(background)), reverse=True)
    return (light + 0.05) / (dark + 0.05)


def validate_palette(colors: dict[str, str]) -> dict[str, float]:
    if set(colors) != set(ROLES):
        raise ValueError("Palette keys must be exactly: " + ", ".join(ROLES))
    for name, value in colors.items():
        if not isinstance(value, str) or not re.fullmatch(r"#[0-9a-fA-F]{6}", value):
            raise ValueError(f"Invalid six-digit RGB color for {name}: {value!r}")
    checks = {
        "body on background": ("foreground", "background", 7.0),
        "body on surface": ("foreground", "surface", 7.0),
        "secondary text on surface": ("muted", "surface", 4.5),
        "selection text": ("foreground", "selected", 4.5),
        "primary button text": ("background", "primary", 4.5),
        "secondary button text": ("background", "secondary", 4.5),
    }
    checks.update({f"{role} syntax": (role, "background", 4.5)
                   for role in ("success", "error", "warning", "blue", "cyan", "secondary")})
    ratios = {}
    for label, (foreground, background, minimum) in checks.items():
        ratio = contrast(colors[foreground], colors[background])
        ratios[label] = ratio
        if ratio < minimum:
            raise ValueError(f"Contrast {label}: {ratio:.2f}:1 is below {minimum}:1")
    semantic = [colors[role].lower() for role in ("success", "error", "warning", "blue", "cyan", "secondary")]
    if len(set(semantic)) != len(semantic):
        raise ValueError("Semantic colors must remain distinct; do not collapse ANSI/diagnostics to an accent")
    return ratios


def render(colors: dict[str, str]) -> dict[str, str]:
    validate_palette(colors)
    c = colors
    ansi = [c[role] for role in ("background", "error", "success", "warning", "blue", "secondary", "cyan", "foreground")]
    bright = [c["muted"], *ansi[1:]]
    ansi_names = ("black", "red", "green", "yellow", "blue", "magenta", "cyan", "white")
    palette = {
        "mPrimary": c["primary"], "mOnPrimary": c["background"],
        "mSecondary": c["secondary"], "mOnSecondary": c["background"],
        "mTertiary": c["blue"], "mOnTertiary": c["background"],
        "mError": c["error"], "mOnError": c["background"],
        "mSurface": c["background"], "mOnSurface": c["foreground"],
        "mSurfaceVariant": c["surface"], "mOnSurfaceVariant": c["muted"],
        "mOutline": c["outline"], "mShadow": c["background"],
        "mHover": c["selected"], "mOnHover": c["foreground"],
        "terminal": {
            "background": c["background"], "foreground": c["foreground"],
            "cursor": c["primary"], "cursorText": c["background"],
            "selectionBg": c["selected"], "selectionFg": c["foreground"],
            "normal": dict(zip(ansi_names, ansi)), "bright": dict(zip(ansi_names, bright)),
        },
    }
    kitty_pairs = {
        "foreground": c["foreground"], "background": c["background"],
        "selection_foreground": c["foreground"], "selection_background": c["selected"],
        "cursor": c["primary"], "cursor_text_color": c["background"],
        "url_color": c["blue"], "active_border_color": c["primary"],
        "inactive_border_color": c["outline"], "active_tab_foreground": c["background"],
        "active_tab_background": c["primary"], "inactive_tab_foreground": c["muted"],
        "inactive_tab_background": c["surface"], "tab_bar_background": c["background"],
    }
    kitty = "# Generated by scripts/moonlit-theme.py; edit palette.json.\n"
    kitty += "# Include AFTER the existing Kitty config; font, size (13pt baseline), and keys are inherited.\n"
    kitty += "background_opacity 0.86\ndynamic_background_opacity yes\n"
    kitty += "".join(f"{key} {value}\n" for key, value in kitty_pairs.items())
    kitty += "".join(f"color{i} {value}\n" for i, value in enumerate(ansi + bright))

    lua = "-- Generated by scripts/moonlit-theme.py; edit palette.json.\n"
    lua += "-- Run after the existing init.lua. No mappings, plugin, font, or workflow changes.\n"
    lua += "local c = " + "{\n" + "".join(f'  {key} = "{value}",\n' for key, value in c.items()) + "}\n"
    lua += '''local hi = function(group, value) vim.api.nvim_set_hl(0, group, value) end
hi("Normal", { fg = c.foreground, bg = "NONE" })
hi("NormalNC", { fg = c.foreground, bg = "NONE" })
hi("NormalFloat", { fg = c.foreground, bg = c.surface })
hi("FloatBorder", { fg = c.outline, bg = c.surface })
hi("FloatTitle", { fg = c.primary, bg = c.surface, bold = true })
hi("SignColumn", { fg = c.muted, bg = "NONE" })
hi("LineNr", { fg = c.muted, bg = "NONE" })
hi("CursorLineNr", { fg = c.primary, bg = "NONE", bold = true })
hi("CursorLine", { bg = c.surface })
hi("Visual", { bg = c.selected })
hi("Search", { fg = c.background, bg = c.warning })
hi("IncSearch", { fg = c.background, bg = c.primary })
hi("StatusLine", { fg = c.foreground, bg = c.surface })
hi("StatusLineNC", { fg = c.muted, bg = c.surface })
hi("WinSeparator", { fg = c.outline })
hi("Pmenu", { fg = c.foreground, bg = c.surface })
hi("PmenuSel", { fg = c.foreground, bg = c.selected })
hi("TabLine", { fg = c.muted, bg = c.surface })
hi("TabLineSel", { fg = c.background, bg = c.primary, bold = true })
hi("TabLineFill", { bg = c.background })
hi("Comment", { fg = c.muted, italic = true })
hi("String", { fg = c.success })
hi("Character", { fg = c.success })
hi("Number", { fg = c.warning })
hi("Boolean", { fg = c.warning })
hi("Constant", { fg = c.warning })
hi("Identifier", { fg = c.foreground })
hi("Function", { fg = c.blue })
hi("Statement", { fg = c.secondary })
hi("Keyword", { fg = c.secondary })
hi("Type", { fg = c.cyan })
hi("Special", { fg = c.primary })
hi("PreProc", { fg = c.primary })
hi("Title", { fg = c.primary, bold = true })
hi("Directory", { fg = c.blue })
hi("ErrorMsg", { fg = c.error })
hi("WarningMsg", { fg = c.warning })
hi("MoreMsg", { fg = c.success })
hi("DiffAdd", { fg = c.success, bg = c.surface })
hi("DiffDelete", { fg = c.error, bg = c.surface })
hi("DiffChange", { fg = c.blue, bg = c.surface })
hi("DiffText", { fg = c.foreground, bg = c.selected })
for suffix, color in pairs({ Error = c.error, Warn = c.warning, Info = c.blue, Hint = c.cyan, Ok = c.success }) do
  hi("Diagnostic" .. suffix, { fg = color })
  hi("DiagnosticSign" .. suffix, { fg = color, bg = "NONE" })
  hi("DiagnosticVirtualText" .. suffix, { fg = color, bg = c.surface })
  hi("DiagnosticUnderline" .. suffix, { sp = color, undercurl = true })
end
for group, target in pairs({ ["@keyword"] = "Keyword", ["@function"] = "Function", ["@type"] = "Type", ["@string"] = "String", ["@comment"] = "Comment", ["@number"] = "Number" }) do
  hi(group, { link = target })
end
'''
    lua += "".join(f'vim.g.terminal_color_{i} = "{value}"\n' for i, value in enumerate(ansi + bright))

    niri = f'''// Generated by scripts/moonlit-theme.py; edit palette.json.
// Opt-in preview include: appearance only, no display/input/binding changes.
layout {{
    background-color "{c['background']}"
    focus-ring {{
        active-color "{c['primary']}"
        inactive-color "{c['outline']}"
        urgent-color "{c['warning']}"
    }}
    shadow {{ color "{c['background']}70"; }}
}}
overview {{ backdrop-color "{c['background']}"; }}
'''
    return dict(zip(OUTPUTS, (json.dumps({"dark": palette}, indent=2) + "\n", kitty, lua, niri)))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="check contrast and derived-file drift without writing")
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1], help="repository root")
    args = parser.parse_args()
    root = args.root.resolve() / "config" / "moonlit"
    try:
        colors = json.loads((root / "palette.json").read_text())
        ratios = validate_palette(colors)
        generated = render(colors)
    except (OSError, ValueError, TypeError) as error:
        parser.exit(1, f"Theme validation failed: {error}\n")
    drift = [name for name, expected in generated.items()
             if not (root / name).exists() or (root / name).read_text() != expected]
    if args.check:
        if drift:
            parser.exit(1, "Generated theme drift: " + ", ".join(drift) + "\nRun scripts/moonlit-theme.py to regenerate.\n")
        print("Moonlit theme: no generated-file drift.")
    else:
        for name, content in generated.items():
            target = root / name
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content)
        print(f"Generated {len(generated)} preview themes from palette.json.")
    print("Solid-swatch contrast: " + ", ".join(f"{name} {value:.2f}:1" for name, value in ratios.items()))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
