# Used explicitly by the Kitty shortcut and :DotfilesGit on both platforms.
gui:
  mouseEvents: true
  showRandomTip: false
  nerdFontsVersion: "3"
  theme:
    activeBorderColor: ["#f2a5c7", bold]
    inactiveBorderColor: ["#574254"]
    optionsTextColor: ["#a7b9ed"]
    selectedLineBgColor: ["#3b2c3b"]
    defaultFgColor: ["#ede5ec"]
    unstagedChangesColor: ["#f08091"]
git:
  autoFetch: false
  autoForwardBranches: none
  autoStageResolvedConflicts: false
update:
  method: never
